# Generated by Django 4.1.4 on 2023-08-21 12:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('managers', models.ManyToManyField(related_name='managed_projects', to='management.customuser')),
                ('users', models.ManyToManyField(related_name='projects', to='management.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, upload_to='images/')),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('resolved', 'Resolved')], max_length=20)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_created', to='management.customuser')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_assigned', to='management.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='management.project')),
            ],
        ),
    ]
