# Generated by Django 4.1.4 on 2023-08-21 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_project_bug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
