# Generated by Django 4.1.4 on 2023-08-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_customuser_user_alter_bug_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='developer',
        ),
        migrations.AddField(
            model_name='project',
            name='qa',
            field=models.ManyToManyField(to='management.user'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='managers',
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='management.user'),
        ),
    ]
