# Generated by Django 4.1.4 on 2023-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_users_project_developer_project_qa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='management.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='qa',
            field=models.ManyToManyField(blank=True, null=True, to='management.user'),
        ),
    ]
