# Generated by Django 4.1.4 on 2023-08-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_project_developer_alter_project_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=20),
        ),
    ]
