# Generated by Django 4.1.4 on 2023-08-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_bug_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='status',
        ),
    ]
