# Generated by Django 4.1.4 on 2023-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_bug_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='status',
        ),
    ]
