# Generated by Django 4.1.4 on 2023-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('resolved', 'Resolved'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
