# Generated by Django 4.1.4 on 2023-08-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rename_user_userprofile_alter_bug_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
