# Generated by Django 4.1.4 on 2023-08-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
