# Generated by Django 4.1.4 on 2023-08-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isdeveloperAssign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isqaAssign',
            field=models.BooleanField(default=False),
        ),
    ]
