# Generated by Django 4.1.4 on 2023-08-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_userprofile_isdeveloperassign_userprofile_isqaassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isdeveloperAssign',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='isqaAssign',
        ),
    ]
