# Generated by Django 4.1.4 on 2023-08-24 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0018_remove_userprofile_isdeveloperassign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='qa',
            field=models.ManyToManyField(blank=True, null=True, related_name='projectsq', to=settings.AUTH_USER_MODEL),
        ),
    ]
