# Generated by Django 4.1.4 on 2023-08-28 09:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_project_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
