# Generated by Django 4.1.4 on 2023-08-28 09:46

from django.db import migrations
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_bug_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=management.models.CustomCloudinaryField(max_length=255, validators=[management.models.validate_file_extension], verbose_name='image'),
        ),
    ]
